### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by taviks** [marlonmarcello/snowpack-plugin-pug#1]
First off, thanks for creating this!

When following the install instructions (from the readme), I get the following: 

```sh
npm ERR! code E401
npm ERR! Unable to authenticate, need: Basic realm="GitHub Package Registry"
```

Ideas?

**Comment by marlonmarcello** [comment]
Hey @yet-another-dev did you authenticate with [Github Packages](https://docs.github.com/en/free-pro-team@latest/packages/guides/configuring-npm-for-use-with-github-packages#installing-a-package)?
I just tested on a separate machine and it worked fine. Let me know how that goes.

**Comment by marlonmarcello** [comment]
@yet-another-dev I just changed how the package is publish and now it's also available on NPM.
Give it a try, just tested on a project and it's great.
Thanks for the feedback, it's unfortunate that GHP still has this barrier of entry.
