### ISSUE TITLE
Not quite sure how to use this?

### ISSUE THREAD

**Issue by sebszocinski** [marlonmarcello/snowpack-plugin-pug#4]
Hey i'm new to Snowpack and just playing around but I always code in pug so I want to get this working first but I'm a little confused coming from Webpack.

I have a `src` folder with an `index.pug` file and then a `public` folder which I assumed would build an `index.html` file into `public` when I run `snowpack dev` but this doesn't seem to be the case?

Can you provide some better instructions in the docs.

**Comment by marlonmarcello** [comment]
Hey there!
I recommend you read the [snowpack docs](https://www.snowpack.dev/) and go through their [Getting started](https://www.snowpack.dev/tutorials/getting-started) section so you can better understand how the folder structure works, by default there is no `src/` folder in snowpack.

After that all you need to do is install this plugin and use `pug` instead of `html`.

**Comment by etjones** [comment]
Thanks for this plugin, Marlon. I had a similar problem to @sebszocinski  and it took me a while to figure out what the disconnect was. I used [create-snowpack-app](https://github.com/snowpackjs/snowpack/tree/main/create-snowpack-app/cli) to set up my projects, which puts javascript/typescript in a `/src` directory and html in a `/public` directory.  

By default, the `/public` directory is set up as static, so Pug files there won't be compiled to HTML files. The solution was to change the `/public` directory to not be static in `snowpack.config.js`;  then the Pug gets compiled to HTML.  

That section of  `snowpack.config.js`  goes from: 
``` javascript
  mount: {
    public: { url: '/', static: true },
    src: { url: '/dist' },
  }
```

to:
``` javascript
  mount: {
    public: { url: '/', static: false },
    src: { url: '/dist' },
  }
```

With luck, anyone else who runs into this problem will find this info.

**Comment by marlonmarcello** [comment]
My bad guys, I honestly never used `create-snowpack-app`. I've only used the basic set up which is pretty much the same one they have on their tutorial.
Thanks for leaving the comment @etjones !

**Comment by marlonmarcello** [comment]
I am going to update the readme with a reference to your comment.

**Comment by etjones** [comment]
Awesome. That should make things easier for some people. 
The Snowpack Quick Start section doesn't talk about `create-snowpack-app`, although it used to. TBH, I don't think I ever would have started using Snowpack if I'd just seen the current Quick Start; way too much manual setup of all the bits and pieces.
