### ISSUE TITLE
npm start downloads a file instead of running in browser

### ISSUE THREAD

**Issue by vincitaylaran** [marlonmarcello/snowpack-plugin-pug#6]
As the title suggests: whenever I run `npm start`, instead of the app running in the browser, it downloads a file in the browser with the compiled HTML.

Not quite sure where I went wrong, but here's what my `snowpack.config.mjs` file looks like:

```
export default {
  mount: {
    public: { url: "/", static: false },
    src: { url: "/dist" },
  },
  plugins: ["@marlonmarcello/snowpack-plugin-pug", "@snowpack/plugin-sass"],
};
```

[Link to repo](https://github.com/vincitaylaran/learning-snowpack)

**Comment by minecrawler** [comment]
Hi @vincitaylaran , I have the same problem. How did you solve it?

**Comment by vincitaylaran** [comment]
Hi @minecrawler . I've reopened the issue. I didn't solve it, unfortunately.

**Comment by minecrawler** [comment]
@vincitaylaran after playing around with it a bit, I came up with a workaround. You have to open the HTML file directly for it to work correctly - and you can do so automatically by for example adding the `openUrl` to your snowpack config:

```js
{
    devOptions: {
        openUrl: 'index.html',
    },
}
```

**Comment by vincitaylaran** [comment]
It works. Much appreciated @minecrawler . Closing the issue again 😅
